In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("bank.csv")

In [3]:
df.head()

Date  Interest_Income  Interest_Expense  Average_Earning_Assets  \
0  2022-01-03        2121958.0            773237                55001045   
1  2022-01-04        2671155.0            518070                54463418   
2  2022-01-05        2131932.0            797921                59771802   
3  2022-01-06        2365838.0            556958                54345760   
4  2022-01-07        2259178.0           1746222                57153768   

   Net_Income  Total_Assets  Shareholder_Equity  Operating_Expenses  \
0   1572212.0      95404302            23496605              811672   
1   1336326.0      86440010            24948600             1030817   
2   1224137.0      88674163            26416438             1345961   
3   1452268.0      97221407            29694095             1289921   
4   3858336.0      98279553            25311499             1432303   

   Operating_Income  Market_Share  Stock_Price  
0           3494178            24          128  
1           3231496            20           63  
2           3692148            22          196  
3           4779685            14          177  
4           4764985            10          103

In [6]:
df.tail()

Date  Interest_Income  Interest_Expense  Average_Earning_Assets  \
518  2023-03-03        2513153.0            551934                55397662   
519  2022-08-23              NaN            866329                50421240   
520  2022-05-04        2106530.0            736175                51910705   
521  2023-01-18        2879989.0            561476                52562469   
522  2023-03-23        2811774.0            737027                58204298   

     Net_Income  Total_Assets  Shareholder_Equity  Operating_Expenses  \
518   1554736.0      96040922            21265898             1068252   
519         NaN      82229180            21551330              921373   
520   1331770.0      98827165            29454531              973260   
521   1810694.0      83138744            25418952             1141416   
522   1793719.0      82627144            22164412             1160244   

     Operating_Income  Market_Share  Stock_Price  
518           4022145            18          169  
519           3842210            23           53  
520           3833525            20          123  
521           4241968            26          142  
522           4478768            14          106

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523 entries, 0 to 522
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Date                    523 non-null    object 
 1   Interest_Income         471 non-null    float64
 2   Interest_Expense        523 non-null    int64  
 3   Average_Earning_Assets  523 non-null    int64  
 4   Net_Income              471 non-null    float64
 5   Total_Assets            523 non-null    int64  
 6   Shareholder_Equity      523 non-null    int64  
 7   Operating_Expenses      523 non-null    int64  
 8   Operating_Income        523 non-null    int64  
 9   Market_Share            523 non-null    int64  
 10  Stock_Price             523 non-null    int64  
dtypes: float64(2), int64(8), object(1)
memory usage: 45.1+ KB


In [5]:
df_clean = df.copy()

In [7]:
df_clean["Interest_Income"].value_counts()

Interest_Income
2121958.0    2
2513153.0    2
2025939.0    2
2829957.0    2
2421909.0    2
            ..
2601661.0    1
2351279.0    1
2838688.0    1
2375713.0    1
2004014.0    1
Name: count, Length: 450, dtype: int64

In [8]:
df_clean["Interest_Income"].unique()

array([2121958., 2671155., 2131932., 2365838., 2259178., 2644167.,
       2110268., 2732180., 2054886., 2137337., 2999890., 2521430.,
       2954698., 2087498., 2899159., 2912756., 2175203., 2191335.,
            nan, 2041090., 2329365., 2064820., 2787201., 2321879.,
       2718315., 2327069., 2776997., 2199041., 2791743., 2103355.,
       2235796., 2214176., 2347449., 2421909., 2989436., 2258795.,
       2486232., 2917040., 2500186., 2870910., 2384681., 2149503.,
       2654811., 2527035., 2648143., 2452366., 2065725., 2129981.,
       2953277., 2905778., 2591723., 2319030., 2328947., 2555839.,
       2902648., 2273538., 2331236., 2565894., 2489492., 2256840.,
       2473254., 2349457., 2665987., 2270936., 2205041., 2698361.,
       2731912., 2417113., 2068148., 2777089., 2648531., 2678843.,
       2910790., 2572843., 2256508., 2803591., 2896942., 2106530.,
       2604365., 2822352., 2460337., 2724839., 2805889., 2459773.,
       2208261., 2764469., 2341097., 2315139., 2171829., 22718

In [17]:
df_clean["Interest_Income"]=df_clean["Interest_Income"].fillna(df_clean["Interest_Income"].mean())

In [18]:
df_clean["Interest_Income"].unique()

array([2121958.        , 2671155.        , 2131932.        ,
       2365838.        , 2259178.        , 2644167.        ,
       2110268.        , 2732180.        , 2054886.        ,
       2137337.        , 2999890.        , 2521430.        ,
       2954698.        , 2087498.        , 2899159.        ,
       2912756.        , 2175203.        , 2191335.        ,
       2493118.29299363, 2041090.        , 2329365.        ,
       2064820.        , 2787201.        , 2321879.        ,
       2718315.        , 2327069.        , 2776997.        ,
       2199041.        , 2791743.        , 2103355.        ,
       2235796.        , 2214176.        , 2347449.        ,
       2421909.        , 2989436.        , 2258795.        ,
       2486232.        , 2917040.        , 2500186.        ,
       2870910.        , 2384681.        , 2149503.        ,
       2654811.        , 2527035.        , 2648143.        ,
       2452366.        , 2065725.        , 2129981.        ,
       2953277.        ,

In [19]:
df_clean["Interest_Income"]=df_clean["Interest_Income"].astype(int)

In [20]:
df_clean["Net_Income"].value_counts()

Net_Income
1572212.0    2
1554736.0    2
1165873.0    2
1854321.0    2
1416366.0    2
            ..
1490457.0    1
1210017.0    1
1450348.0    1
1882875.0    1
3768400.0    1
Name: count, Length: 450, dtype: int64

In [21]:
df_clean["Net_Income"].unique()

array([1572212., 1336326., 1224137., 1452268., 3858336., 1297881.,
       1363476., 1351707., 1684733., 1510585., 1691757., 1390719.,
       1479361., 1101371., 1562997., 1192192., 1150322., 1021172.,
            nan, 1996121., 1577564., 1581780., 1708362., 1513319.,
       1780298., 1876031., 1989859., 1222320., 1417978., 1011046.,
       1228071., 1378165., 3417324., 1416366., 3971502., 1266997.,
       1645188., 1482615., 1415008., 1761379., 1205550., 1244883.,
       1638418., 1460514., 1949491., 1671210., 1929616., 1121789.,
       1700780., 1563178., 1066017., 1178376., 1688281., 2998274.,
       1656884., 1624712., 1801480., 1693264., 1841344., 1558296.,
       1393276., 1730026., 1607847., 1055337., 1024354., 1045186.,
       1552433., 1427236., 1610411., 1499883., 1730546., 1613217.,
       1285195., 1575762., 1616036., 1125995., 1245690., 1331770.,
       1793392., 1428988., 1939024., 1180553., 3121392., 1880438.,
       1259568., 1319278., 1151563., 1656701., 1699983., 16146

In [22]:
df_clean["Net_Income"] = df_clean["Net_Income"].fillna(df_clean["Net_Income"].mean())

In [25]:
df_clean["Net_Income"]=df_clean["Net_Income"].astype(int)

In [26]:
df_clean.head()

Date  Interest_Income  Interest_Expense  Average_Earning_Assets  \
0  2022-01-03          2121958            773237                55001045   
1  2022-01-04          2671155            518070                54463418   
2  2022-01-05          2131932            797921                59771802   
3  2022-01-06          2365838            556958                54345760   
4  2022-01-07          2259178           1746222                57153768   

   Net_Income  Total_Assets  Shareholder_Equity  Operating_Expenses  \
0     1572212      95404302            23496605              811672   
1     1336326      86440010            24948600             1030817   
2     1224137      88674163            26416438             1345961   
3     1452268      97221407            29694095             1289921   
4     3858336      98279553            25311499             1432303   

   Operating_Income  Market_Share  Stock_Price  
0           3494178            24          128  
1           3231496            20           63  
2           3692148            22          196  
3           4779685            14          177  
4           4764985            10          103

In [28]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"])

In [29]:
df_clean.head()

Date  Interest_Income  Interest_Expense  Average_Earning_Assets  \
0 2022-01-03          2121958            773237                55001045   
1 2022-01-04          2671155            518070                54463418   
2 2022-01-05          2131932            797921                59771802   
3 2022-01-06          2365838            556958                54345760   
4 2022-01-07          2259178           1746222                57153768   

   Net_Income  Total_Assets  Shareholder_Equity  Operating_Expenses  \
0     1572212      95404302            23496605              811672   
1     1336326      86440010            24948600             1030817   
2     1224137      88674163            26416438             1345961   
3     1452268      97221407            29694095             1289921   
4     3858336      98279553            25311499             1432303   

   Operating_Income  Market_Share  Stock_Price  
0           3494178            24          128  
1           3231496            20           63  
2           3692148            22          196  
3           4779685            14          177  
4           4764985            10          103

In [30]:
df_clean["Year"] = pd.to_datetime(df_clean["Date"]).dt.year
df_clean["Month"] = pd.to_datetime(df_clean["Date"]).dt.month
df_clean["Day"] = pd.to_datetime(df_clean["Date"]).dt.day

In [31]:
df_clean.head()

Date  Interest_Income  Interest_Expense  Average_Earning_Assets  \
0 2022-01-03          2121958            773237                55001045   
1 2022-01-04          2671155            518070                54463418   
2 2022-01-05          2131932            797921                59771802   
3 2022-01-06          2365838            556958                54345760   
4 2022-01-07          2259178           1746222                57153768   

   Net_Income  Total_Assets  Shareholder_Equity  Operating_Expenses  \
0     1572212      95404302            23496605              811672   
1     1336326      86440010            24948600             1030817   
2     1224137      88674163            26416438             1345961   
3     1452268      97221407            29694095             1289921   
4     3858336      98279553            25311499             1432303   

   Operating_Income  Market_Share  Stock_Price  Year  Month  Day  
0           3494178            24          128  2022      1    3  
1           3231496            20           63  2022      1    4  
2           3692148            22          196  2022      1    5  
3           4779685            14          177  2022      1    6  
4           4764985            10          103  2022      1    7

In [34]:
df_clean.drop(['Date'], axis=1, inplace=True)

In [35]:
df_clean.head()

Interest_Income  Interest_Expense  Average_Earning_Assets  Net_Income  \
0          2121958            773237                55001045     1572212   
1          2671155            518070                54463418     1336326   
2          2131932            797921                59771802     1224137   
3          2365838            556958                54345760     1452268   
4          2259178           1746222                57153768     3858336   

   Total_Assets  Shareholder_Equity  Operating_Expenses  Operating_Income  \
0      95404302            23496605              811672           3494178   
1      86440010            24948600             1030817           3231496   
2      88674163            26416438             1345961           3692148   
3      97221407            29694095             1289921           4779685   
4      98279553            25311499             1432303           4764985   

   Market_Share  Stock_Price  Year  Month  Day  
0            24          128  2022      1    3  
1            20           63  2022      1    4  
2            22          196  2022      1    5  
3            14          177  2022      1    6  
4            10          103  2022      1    7